version: '3'

services:
  db:
    image: postgres:10.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    expose:
      - 5432
  api:
    build: .
    command: npm run start:dev
    volumes:
      - .:/code
    ports:
      - "8081:8081"
    depends_on:
      - db